version: '3'
services:
  app:
    image: badconfig/books
    container_name: app
    tty: true
    environment:
      - DATABASE_URL=postgres://main:NavwNgTnxyWsz7hy5yRmEKC4X@books_postgres:5432/diesel_db
      - MONGO_URL=mongodb://main:NavwNgTnxyWsz7hy5yRmEKC4X@books_mongo:27017/mongo
    ports:
      - "8088:8088"
    volumes:
          - ./migrations:/app/migrations/
    networks:
      - app-network
  books_mongo:
    image: mongo
    container_name: books_mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo_books:/data/db
    networks:
      - app-network
  books_postgres:
    image: "postgres:12.6"
    container_name: books_postgres
    restart: unless-stopped
    ports:
      - "7000:5432"
    environment:
      POSTGRES_DB: diesel_db
      POSTGRES_PASSWORD: NavwNgTnxyWsz7hy5yRmEKC4X
      POSTGRES_USER: main
    networks:
      - app-network
    volumes:
      - pg_books:/var/lib/postgresql/data
  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./html:/var/tools/
      - ./public/:/var/tools/public/
    ports:
      - "80:80"
    networks:
      - app-network
volumes:
  pg_books:
  mongo_books:
networks:
  app-network:
    driver: bridge

